In [2]:
import pandas as pd
import string
from collections import Counter
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
# import spacy
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.pipeline import Pipeline

In [3]:
# df = pd.read_csv('/kaggle/input/datasets/omar2716/emails-dataset/spam_and_ham_classification.csv')
df= pd.read_csv('spam_and_ham_classification.csv')

In [4]:
df

     label                                               text
0      ham  into the kingdom of god and those that are ent...
1     spam  there was flow at hpl meter 1505 on april firs...
2      ham  take a look at this one campaign for bvyhprice...
3     spam  somu wrote actually thats what i was looking f...
4     spam  fathi boudra wrote i fixed the issue in the sv...
...    ...                                                ...
9984   ham  this would be a great tragedy for all concerne...
9985   ham  hello , welcome to medzonline filamentous shop...
9986   ham  this is amazing stuff add some inches fast saf...
9987  spam  author jra date escapenumber escapenumber esca...
9988   ham  anatrim escapenumber the newest and most attra...

[9989 rows x 2 columns]

In [5]:
df.head()

  label                                               text
0   ham  into the kingdom of god and those that are ent...
1  spam  there was flow at hpl meter 1505 on april firs...
2   ham  take a look at this one campaign for bvyhprice...
3  spam  somu wrote actually thats what i was looking f...
4  spam  fathi boudra wrote i fixed the issue in the sv...

In [6]:
df.tail()

     label                                               text
9984   ham  this would be a great tragedy for all concerne...
9985   ham  hello , welcome to medzonline filamentous shop...
9986   ham  this is amazing stuff add some inches fast saf...
9987  spam  author jra date escapenumber escapenumber esca...
9988   ham  anatrim escapenumber the newest and most attra...

In [7]:
df.shape

(9989, 2)

In [8]:
df.size

19978

In [9]:
df.sample(20)

     label                                               text
8602   ham  christmass s @ | e - w ! ndows xp home\nwe hav...
8707   ham  5 , meridian east\nleicester le 3 2 wz\nleices...
3788  spam  subscribe change profile contact us long term ...
1057  spam  hi the silverman's paper introduction offer ho...
7491  spam  to : all enron employees :\nthis is a reminder...
462   spam  ?\n- - - - - original message - - - - -\nfrom ...
2334   ham  youcansave . com\n4330 commerce drive\nbatavia...
7718  spam  dear richard ,\nthanks for your message - i ju...
4032   ham  our warmest greetings unique proposal for you ...
112    ham  dear henna plg uwaterloo ca http kkeioop com w...
654    ham  want fuck by your dick with handsome woman vis...
3321   ham  price for viagra sildenafil escapenumbermg x e...
4491   ham                        click here to order today\n
6222   ham  quality ink supplies for less at escapenumberi...
5389   ham  welcome to johnson\nhome products services j ....
9914   ham  this gem is really movable lookup asvpcurrent ...
2116  spam   escapenumber breaking news escapenumber home ...
6291   ham  g?t th? low?st pric? avaliabl? , you d?s?rv? i...
2774   ham  take adventage symb ol chvccurrent escapenumbe...
6020   ham  cheers online casino is waiting for your stake...

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9989 entries, 0 to 9988
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   label   9989 non-null   object
 1   text    9989 non-null   object
dtypes: object(2)
memory usage: 156.2+ KB

In [11]:
df = df.dropna()
all_words = ' '.join(df.text).split()

In [12]:
len(all_words)

2747483

In [13]:
count = Counter(all_words)
count

Counter({'escapenumber': 133208,
         'the': 85264,
         'to': 56587,
         '.': 52672,
         'and': 42360,
         '-': 40970,
         'of': 40427,
         ',': 39261,
         'a': 36859,
         'in': 28900,
         'escapelong': 24634,
         'for': 22671,
         'you': 22222,
         'is': 21731,
         'i': 19917,
         '/': 19489,
         'that': 17078,
         ':': 16702,
         'this': 16485,
         'on': 16397,
         'with': 13249,
         'it': 13230,
         'be': 12177,
         'your': 12109,
         'as': 11360,
         'from': 10399,
         'are': 10055,
         'have': 10014,
         'http': 9844,
         'at': 9395,
         'not': 9285,
         'or': 9107,
         'we': 9072,
         'com': 8889,
         'will': 8633,
         'by': 8574,
         'if': 7868,
         "'": 7816,
         's': 7406,
         'our': 6959,
         'all': 6834,
         'r': 6458,
         'but': 5908,
         ')': 5871,
         'an': 5825,
         '_': 5810,
         'enron': 5723,
         'was': 5531,
         '(': 5487,
         '@': 5468,
         'can': 5451,
         'more': 5231,
         'do': 5213,
         'c': 5147,
         'my': 5112,
         'org': 5109,
         'has': 4744,
         'please': 4716,
         '"': 4716,
         'x': 4668,
         'www': 4567,
         'no': 4526,
         'new': 4465,
         'e': 4377,
         'help': 4245,
         'one': 4241,
         '?': 4197,
         'may': 4195,
         'ect': 4087,
         'any': 3963,
         'would': 3962,
         'per': 3842,
         'me': 3841,
         '>': 3834,
         '!': 3784,
         '$': 3751,
         'about': 3589,
         'samba': 3584,
         'list': 3579,
         'what': 3569,
         'so': 3523,
         'he': 3506,
         'which': 3496,
         'get': 3438,
         'time': 3419,
         'out': 3393,
         'up': 3350,
         'now': 3350,
         'company': 3255,
         't': 3217,
         'us': 3213,
         'only': 3201,
         'am': 3197,
         'there': 3174,
         'here': 3160,
         'they': 3151,
         'escapenumberd': 2955,
         'some': 2948,
         'like': 2912,
         'source': 2884,
         'pills': 2848,
         ';': 2837,
         'price': 2828,
         'been': 2781,
         '=': 2758,
         'news': 2717,
         'email': 2657,
         'use': 2650,
         'see': 2633,
         'said': 2627,
         'their': 2624,
         'its': 2620,
         'his': 2601,
         'html': 2592,
         'escapenumbermg': 2574,
         'message': 2531,
         'when': 2530,
         'mail': 2529,
         'just': 2507,
         'ch': 2504,
         'stat': 2490,
         'data': 2459,
         'also': 2445,
         'other': 2417,
         'ethz': 2396,
         'need': 2393,
         'how': 2393,
         'information': 2381,
         'p': 2376,
         'should': 2326,
         '|': 2316,
         'know': 2302,
         'into': 2295,
         'business': 2267,
         'guide': 2266,
         'subject': 2255,
         'make': 2248,
         '1': 2212,
         'read': 2205,
         'had': 2205,
         'd': 2198,
         'posting': 2198,
         'could': 2182,
         'code': 2181,
         'these': 2144,
         'than': 2126,
         'branches': 2071,
         '2': 2044,
         'pm': 2036,
         'over': 2034,
         'hou': 2027,
         'who': 2025,
         'thanks': 2019,
         '*': 1975,
         'work': 1973,
         'then': 1959,
         'day': 1959,
         'free': 1959,
         'file': 1958,
         'name': 1936,
         'mailing': 1915,
         '3': 1899,
         'item': 1889,
         'provide': 1881,
         'them': 1818,
         'save': 1786,
         'after': 1781,
         'money': 1772,
         'were': 1768,
         'de': 1757,
         'project': 1757,
         'm': 1748,
         'first': 1729,
         'very': 1728,
         'o': 1720,
         'people': 1719,
         'want': 1708,
         'power': 1679,
         'net': 1676,
         'b': 1673,
         'mailman': 1666,
         'wrote': 1656,
         'ctdb': 1631,
         'way': 1625,
         'best': 1621,
         'click': 1612,
         'go': 1595,
         'ca': 1573,
         'h': 1570,
         'two': 1569,
         'most': 1565,
         'self': 1550,
         'listinfo': 1535,
         'unsubscribe': 1525,
         'gas': 1521,
         'y': 1519,
         'contact': 1510,
         'energy': 1507,
         '2001': 1501,
         'her': 1481,
         'u': 1481,
         'low': 1480,
         'such': 1475,
         'service': 1474,
         'using': 1450,
         'system': 1448,
         'report': 1431,
         'much': 1430,
         'because': 1425,
         'perl': 1417,
         '2000': 1408,
         'does': 1402,
         'through': 1390,
         '5': 1381,
         'take': 1380,
         'rev': 1380,
         'well': 1375,
         'cc': 1370,
         'math': 1364,
         'year': 1364,
         'many': 1360,
         'she': 1357,
         'cnn': 1355,
         '10': 1350,
         'available': 1344,
         'number': 1336,
         'line': 1335,
         '&': 1333,
         'world': 1327,
         'good': 1315,
         'last': 1305,
         'next': 1304,
         'think': 1303,
         'before': 1290,
         '00': 1286,
         'inc': 1286,
         'return': 1285,
         'where': 1273,
         'today': 1268,
         "don't": 1268,
         'market': 1264,
         'call': 1260,
         'find': 1256,
         'sent': 1255,
         'products': 1252,
         "it's": 1250,
         'contained': 1248,
         '0': 1239,
         'back': 1234,
         'home': 1226,
         '%': 1225,
         'high': 1222,
         '\x95': 1221,
         'l': 1220,
         'right': 1207,
         'web': 1207,
         'group': 1204,
         'made': 1197,
         'state': 1185,
         'look': 1183,
         'even': 1180,
         'include': 1179,
         'each': 1170,
         'health': 1167,
         'error': 1162,
         'software': 1160,
         'date': 1160,
         '4': 1156,
         'quality': 1148,
         'send': 1144,
         'being': 1141,
         're': 1139,
         'j': 1127,
         'under': 1118,
         'order': 1112,
         'n': 1110,
         'online': 1107,
         'site': 1105,
         'those': 1104,
         'version': 1102,
         'off': 1101,
         'set': 1097,
         'following': 1097,
         'commented': 1095,
         'full': 1093,
         'minimal': 1092,
         'years': 1092,
         'looking': 1090,
         'https': 1088,
         'week': 1087,
         'deal': 1077,
         'great': 1074,
         'end': 1073,
         'reproducible': 1071,
         'part': 1069,
         'sid': 1067,
         'test': 1064,
         'same': 1060,
         'since': 1060,
         'him': 1059,
         'watch': 1055,
         '000': 1055,
         'long': 1051,
         'without': 1049,
         'product': 1049,
         'every': 1045,
         'change': 1045,
         'within': 1044,
         'receive': 1040,
         'address': 1037,
         'type': 1036,
         'value': 1033,
         'top': 1033,
         'while': 1033,
         'used': 1021,
         'office': 1020,
         'aescapenumber': 1019,
         'prices': 1007,
         'struct': 1006,
         'program': 1005,
         'forward': 1000,
         'pl': 1000,
         'try': 994,
         'w': 993,
         'let': 985,
         'modified': 985,
         'buy': 984,
         'id': 981,
         'offer': 979,
         'vince': 978,
         'still': 978,
         'adobe': 973,
         'based': 971,
         'start': 970,
         'security': 970,
         'dear': 965,
         'really': 961,
         'too': 961,
         'statements': 955,
         'original': 952,
         '11': 949,
         'services': 946,
         "i'm": 942,
         'million': 934,
         '+': 933,
         'story': 932,
         'retail': 931,
         'function': 930,
         'hi': 928,
         'mr': 907,
         'visit': 905,
         'future': 904,
         'current': 904,
         'network': 900,
         'companies': 898,
         'both': 897,
         'customers': 896,
         'give': 892,
         'support': 891,
         'status': 890,
         'did': 889,
         'check': 888,
         'life': 885,
         'why': 885,
         '7': 885,
         'windows': 877,
         'problem': 871,
         'size': 869,
         'down': 868,
         'account': 859,
         'own': 850,
         'investment': 850,
         'might': 848,
         'lib': 848,
         'key': 847,
         'below': 846,
         'june': 846,
         'cgi': 844,
         'open': 840,
         'must': 839,
         'better': 839,
         '6': 839,
         '01': 838,
         'going': 838,
         'ctx': 834,
         'slashdot': 832,
         'corp': 831,
         'customer': 830,
         'case': 828,
         '8': 827,
         'bush': 822,
         'article': 822,
         'internet': 821,
         'come': 817,
         'debian': 817,
         'info': 816,
         'f': 813,
         'something': 812,
         'speakup': 810,
         'bank': 805,
         'view': 804,
         'anatrim': 802,
         'sure': 797,
         'say': 796,
         'rights': 792,
         'request': 789,
         'result': 788,
         '#': 788,
         'stock': 783,
         'special': 781,
         'utc': 780,
         'tdb': 780,
         'regards': 777,
         'add': 775,
         'thank': 767,
         'show': 765,
         'found': 762,
         'three': 759,
         'term': 758,
         'few': 757,
         'additional': 756,
         'process': 752,
         'management': 750,
         '30': 747,
         'friday': 747,
         'g': 746,
         'credit': 741,
         'old': 741,
         'th': 740,
         'days': 739,
         'possible': 739,
         'real': 739,
         'month': 737,
         'private': 734,
         'between': 732,
         'access': 728,
         'questions': 728,
         'able': 728,
         'again': 728,
         'place': 725,
         'true': 719,
         'co': 717,
         'cost': 717,
         'user': 713,
         'copyright': 712,
         'already': 711,
         'john': 706,
         'release': 705,
         'lists': 703,
         'results': 703,
         'another': 702,
         'package': 698,
         'index': 697,
         'risk': 691,
         '12': 691,
         'monday': 690,
         'public': 682,
         'less': 680,
         'drugs': 679,
         'na': 679,
         'team': 676,
         'server': 675,
         'eescapenumber': 675,
         'technology': 672,
         'however': 669,
         'escapenumber°c': 665,
         'microsoft': 664,
         'jun': 662,
         'video': 662,
         'bin': 661,
         'fax': 661,
         'context': 659,
         'different': 657,
         'working': 653,
         'always': 653,
         'run': 653,
         'posted': 652,
         'log': 651,
         'uk': 651,
         'attached': 651,
         'april': 650,
         'thursday': 650,
         'including': 649,
         'research': 648,
         'website': 647,
         'v': 645,
         'terms': 644,
         'financial': 643,
         'due': 641,
         'development': 641,
         '9': 640,
         'received': 639,
         'little': 638,
         'create': 638,
         'point': 637,
         'suite': 634,
         'never': 633,
         'example': 632,
         'print': 630,
         'president': 629,
         'meeting': 627,
         'level': 627,
         'transaction': 626,
         'got': 625,
         'works': 623,
         'learn': 621,
         'link': 620,
         'hope': 620,
         'man': 618,
         'american': 618,
         'says': 615,
         'houston': 614,
         'around': 612,
         'trading': 609,
         'times': 609,
         'international': 608,
         '20': 606,
         'write': 605,
         'model': 604,
         'york': 604,
         'keep': 603,
         'stop': 603,
         'null': 602,
         'center': 601,
         '\\': 600,
         'shares': 599,
         'phone': 598,
         'local': 596,
         'securities': 595,
         'escapenumbere': 593,
         'reply': 590,
         'text': 589,
         'generic': 589,
         'position': 588,
         'above': 586,
         'hk': 584,
         'professional': 584,
         'given': 582,
         'thing': 580,
         'months': 580,
         'parrot': 580,
         'short': 579,
         'form': 578,
         'means': 576,
         'trade': 576,
         'close': 575,
         'linux': 574,
         'dept': 574,
         'files': 573,
         'currently': 573,
         'bill': 572,
         'ac': 571,
         'until': 571,
         'don': 570,
         'control': 569,
         'options': 569,
         'things': 567,
         'build': 567,
         'put': 561,
         'target': 560,
         'stories': 559,
         'early': 558,
         'interest': 557,
         'fact': 556,
         'reserved': 555,
         'offers': 553,
         'else': 553,
         'during': 552,
         '\\\\': 552,
         'note': 552,
         'string': 551,
         'pay': 550,
         'act': 549,
         'university': 549,
         '02': 548,
         'escapenumberonly': 547,
         'kaminski': 545,
         'once': 545,
         'daily': 543,
         'computer': 543,
         'total': 542,
         'issue': 542,
         'links': 542,
         'cbs': 542,
         'hours': 541,
         'purchase': 536,
         'common': 536,
         'big': 535,
         'viagra': 535,
         'provided': 534,
         'trying': 533,
         'industry': 533,
         'manager': 533,
         'course': 532,
         'tuesday': 532,
         'wish': 531,
         'en': 529,
         'further': 528,
         'done': 528,
         'complete': 527,
         'major': 527,
         'media': 527,
         'names': 527,
         'california': 527,
         'beginners': 525,
         'natural': 525,
         '15': 525,
         'yes': 524,
         'believe': 523,
         'et': 522,
         'oil': 521,
         'cannot': 520,
         'talloc': 520,
         'sugar': 520,
         'funds': 518,
         'second': 517,
         'revision': 516,
         'feel': 516,
         'cescapenumber': 514,
         'alert': 513,
         'websvn': 512,
         'details': 512,
         'against': 512,
         'global': 511,
         'lot': 510,
         'comments': 508,
         'page': 507,
         'changes': 507,
         'general': 505,
         'weather': 504,
         'library': 503,
         'states': 503,
         'required': 503,
         'via': 502,
         'yet': 501,
         'soon': 501,
         'cash': 501,
         'char': 500,
         'country': 498,
         'advice': 498,
         'nothing': 497,
         'agreement': 496,
         'forwarded': 496,
         'legal': 495,
         'shall': 494,
         'non': 494,
         'though': 493,
         'tests': 491,
         'canadianpharmacy': 490,
         'discuss': 490,
         'copy': 489,
         'configure': 489,
         'small': 487,
         'away': 487,
         '`': 487,
         'space': 486,
         'rate': 486,
         'wednesday': 486,
         'share': 485,
         'section': 483,
         'search': 483,
         'final': 483,
         'yourself': 483,
         'mark': 482,
         'drug': 482,
         'license': 482,
         'ever': 482,
         'law': 481,
         'update': 481,
         'k': 481,
         'la': 481,
         'live': 479,
         'plan': 479,
         'anything': 478,
         'int': 478,
         'yours': 477,
         'tridge': 477,
         'past': 475,
         'event': 474,
         'upon': 473,
         'fescapenumber': 473,
         'third': 472,
         'systems': 471,
         'pro': 471,
         'having': 471,
         'issues': 470,
         '25': 470,
         'july': 469,
         'uwaterloo': 469,
         'person': 468,
         'markets': 468,
         'whether': 467,
         'problems': 467,
         'department': 467,
         'morning': 467,
         'ok': 466,
         'image': 464,
         'parent': 464,
         'review': 462,
         'root': 461,
         'getting': 460,
         'hello': 458,
         '50': 456,
         'events': 456,
         'billion': 456,
         'weeks': 455,
         'tell': 454,
         'book': 454,
         'follow': 454,
         'sell': 453,
         'united': 453,
         'action': 452,
         'expected': 451,
         'left': 451,
         'client': 450,
         'far': 450,
         'xp': 450,
         'national': 450,
         'canadian': 450,
         'continue': 450,
         'needs': 448,
         'easy': 448,
         'doing': 447,
         'trunk': 446,
         'st': 445,
         'notice': 444,
         'transfer': 443,
         'large': 442,
         'aol': 442,
         'patch': 441,
         'simply': 440,
         'increase': 439,
         'braille': 439,
         'class': 439,
         'government': 439,
         'men': 439,
         'performance': 438,
         'fund': 437,
         'called': 436,
         'uwo': 436,
         'fast': 436,
         'family': 436,
         'descapenumber': 436,
         'house': 435,
         'pillescapenumber': 435,
         'broker': 434,
         'weight': 433,
         'david': 432,
         'remove': 430,
         'length': 429,
         'alternative': 429,
         'begin': 429,
         'apr': 429,
         'become': 429,
         'making': 429,
         'strong': 429,
         'etc': 428,
         'told': 428,
         'important': 427,
         'messages': 427,
         '04': 427,
         'privacy': 426,
         'simple': 425,
         'smb': 425,
         'interested': 425,
         'certain': 424,
         'direct': 423,
         'usa': 422,
         '713': 422,
         'later': 422,
         'rpc': 422,
         'bit': 421,
         'join': 421,
         'content': 420,
         'related': 420,
         'sales': 419,
         'nt': 419,
         'needed': 418,
         'several': 417,
         'tried': 417,
         "i've": 417,
         'mean': 416,
         'bescapenumber': 416,
         'capital': 415,
         'immediately': 414,
         'thought': 414,
         "doesn't": 413,
         'failed': 413,
         'school': 412,
         'anyone': 412,
         '03': 412,
         'solution': 411,
         'question': 411,
         'least': 411,
         'either': 410,
         'experience': 410,
         '09': 410,
         'jones': 409,
         'medications': 407,
         'america': 407,
         'store': 407,
         'contract': 406,
         'actually': 405,
         'vescapenumber': 404,
         'job': 404,
         'latest': 404,
         'receiving': 403,
         'announced': 402,
         'delivery': 402,
         'hard': 402,
         'ip': 401,
         'install': 401,
         'script': 401,
         'path': 400,
         'regarding': 400,
         'percent': 399,
         'ago': 399,
         'move': 399,
         'matter': 398,
         'marketing': 397,
         'five': 396,
         'ees': 396,
         'dollars': 394,
         'el': 394,
         'face': 393,
         "that's": 392,
         'box': 392,
         '2004': 392,
         'application': 390,
         'brand': 390,
         'domain': 390,
         'wind': 390,
         'friend': 389,
         'michael': 389,
         'personal': 388,
         'ask': 388,
         'default': 387,
         'white': 387,
         'press': 387,
         'member': 387,
         'minutes': 387,
         'love': 386,
         'louise': 386,
         'recent': 385,
         'download': 385,
         'yahoo': 385,
         'die': 385,
         'safe': 384,
         'limited': 384,
         'author': 383,
         'plot': 383,
         'asked': 382,
         'opportunity': 382,
         'hour': 382,

In [14]:
df.label.info()

<class 'pandas.core.series.Series'>
RangeIndex: 9989 entries, 0 to 9988
Series name: label
Non-Null Count  Dtype
--------------  -----
9989 non-null   object
dtypes: object(1)
memory usage: 78.2+ KB

In [15]:
df.describe()

       label                                               text
count   9989                                               9989
unique     2                                               9989
top      ham  into the kingdom of god and those that are ent...
freq    5294                                                  1

In [16]:
df.label.value_counts()

label
ham     5294
spam    4695
Name: count, dtype: int64

> Cleaning Data

In [17]:
df.isna().sum()

label    0
text     0
dtype: int64

In [18]:
df.duplicated().sum()

0

In [19]:
df = df.drop_duplicates()
df = df.dropna()

# حذف علامات الترقيم

In [20]:
punc = string.punctuation

In [21]:
punTable = str.maketrans('','',punc)

In [22]:
df.text = df.text.str.translate(punTable)

# حروف صغيرة

In [23]:
df.text = df.text.str.lower()

# حذف الكلمات الشائعة

In [24]:
# nltk.download('stopwords')
# nltk.download('punkt')
stopWords = set(stopwords.words('english'))

In [25]:
df.text = df.text.str.split()

In [26]:
df

     label                                               text
0      ham  [into, the, kingdom, of, god, and, those, that...
1     spam  [there, was, flow, at, hpl, meter, 1505, on, a...
2      ham  [take, a, look, at, this, one, campaign, for, ...
3     spam  [somu, wrote, actually, thats, what, i, was, l...
4     spam  [fathi, boudra, wrote, i, fixed, the, issue, i...
...    ...                                                ...
9984   ham  [this, would, be, a, great, tragedy, for, all,...
9985   ham  [hello, welcome, to, medzonline, filamentous, ...
9986   ham  [this, is, amazing, stuff, add, some, inches, ...
9987  spam  [author, jra, date, escapenumber, escapenumber...
9988   ham  [anatrim, escapenumber, the, newest, and, most...

[9989 rows x 2 columns]

In [27]:
df.text = df.text.apply(lambda x:[word for word in x if word not in stopWords])

In [28]:
df

     label                                               text
0      ham  [kingdom, god, entering, lord, pardon, escapen...
1     spam  [flow, hpl, meter, 1505, april, first, deal, t...
2      ham  [take, look, one, campaign, bvyhprice, escapen...
3     spam  [somu, wrote, actually, thats, looking, l, r, ...
4     spam  [fathi, boudra, wrote, fixed, issue, svn, repo...
...    ...                                                ...
9984   ham  [would, great, tragedy, concerned, situation, ...
9985   ham  [hello, welcome, medzonline, filamentous, shop...
9986   ham  [amazing, stuff, add, inches, fast, safe, effe...
9987  spam  [author, jra, date, escapenumber, escapenumber...
9988   ham  [anatrim, escapenumber, newest, attracting, pr...

[9989 rows x 2 columns]

In [29]:
df.text= df.text.apply(lambda x:' '.join([word for word in x if len(word) > 2]))

In [30]:
df

     label                                               text
0      ham  kingdom god entering lord pardon escapenumber ...
1     spam  flow hpl meter 1505 april first deal ticket de...
2      ham  take look one campaign bvyhprice escapenumber ...
3     spam  somu wrote actually thats looking user entered...
4     spam  fathi boudra wrote fixed issue svn repo rev es...
...    ...                                                ...
9984   ham  would great tragedy concerned situation digiti...
9985   ham  hello welcome medzonline filamentous shop plea...
9986   ham  amazing stuff add inches fast safe effective s...
9987  spam  author jra date escapenumber escapenumber esca...
9988   ham  anatrim escapenumber newest attracting product...

[9989 rows x 2 columns]

# تحويل الكلمات إلى جذورها الأساسية أو صيغتها المعيارية.

In [31]:
# nlp = spacy.load("en_core_web_sm")
# df['text'] = df['text'].apply(lambda x: " ".join([token.lemma_ for token in nlp(str(x))]))

# تقسيم البيانات

In [32]:
x = df.text
y = df.label

In [33]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42,stratify=y) # stratify=y  يضمن ان النموذج يوازن بين البيانات بدون تحيز

In [34]:
tfidf=TfidfVectorizer()

In [49]:
x_train_vec = tfidf.fit_transform(x_train) #fit تبني القاموس transform تطبق القاموس fit_transform تعمل العملين 
x_test_vec = tfidf.transform(x_test)

# pipeline

In [56]:
model_pipeline = Pipeline([("tfidf",TfidfVectorizer(lowercase=True,stop_words="english",max_features=5000,)),("model",LinearSVC())])
model_pipeline.fit(x_train,y_train)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(max_features=5000, stop_words='english')),
                ('model', LinearSVC())])

# بنا النموذج

In [36]:
model = MultinomialNB()

In [37]:
model.fit(x_train_vec,y_train)

MultinomialNB()

In [38]:
pred = model.predict(x_test_vec)

In [39]:
pred

array(['spam', 'spam', 'spam', ..., 'ham', 'spam', 'spam'], dtype='<U4')

In [40]:
acc = accuracy_score(pred,y_test)

In [41]:
acc

0.970970970970971

In [42]:
classification = classification_report(pred,y_test)

In [43]:
print(classification)

              precision    recall  f1-score   support

         ham       0.96      0.98      0.97      1035
        spam       0.98      0.96      0.97       963

    accuracy                           0.97      1998
   macro avg       0.97      0.97      0.97      1998
weighted avg       0.97      0.97      0.97      1998

In [44]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier

In [45]:
model = LinearSVC()

In [46]:
model.fit(x_train_vec,y_train)

LinearSVC()

In [47]:
pred = model.predict(x_test_vec)

In [48]:
acc = accuracy_score(pred,y_test)
acc

0.9824824824824825