In [1]:
import pandas as pd
import string
from collections import Counter
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import spacy
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [2]:
df = pd.read_csv('/kaggle/input/datasets/omar2716/emails-dataset/spam_and_ham_classification.csv')

In [3]:
df

     label                                               text
0      ham  into the kingdom of god and those that are ent...
1     spam  there was flow at hpl meter 1505 on april firs...
2      ham  take a look at this one campaign for bvyhprice...
3     spam  somu wrote actually thats what i was looking f...
4     spam  fathi boudra wrote i fixed the issue in the sv...
...    ...                                                ...
9984   ham  this would be a great tragedy for all concerne...
9985   ham  hello , welcome to medzonline filamentous shop...
9986   ham  this is amazing stuff add some inches fast saf...
9987  spam  author jra date escapenumber escapenumber esca...
9988   ham  anatrim escapenumber the newest and most attra...

[9989 rows x 2 columns]

In [4]:
df.head()

  label                                               text
0   ham  into the kingdom of god and those that are ent...
1  spam  there was flow at hpl meter 1505 on april firs...
2   ham  take a look at this one campaign for bvyhprice...
3  spam  somu wrote actually thats what i was looking f...
4  spam  fathi boudra wrote i fixed the issue in the sv...

In [5]:
df.tail()

     label                                               text
9984   ham  this would be a great tragedy for all concerne...
9985   ham  hello , welcome to medzonline filamentous shop...
9986   ham  this is amazing stuff add some inches fast saf...
9987  spam  author jra date escapenumber escapenumber esca...
9988   ham  anatrim escapenumber the newest and most attra...

In [6]:
df.shape

(9989, 2)

In [7]:
df.size

19978

In [8]:
df.sample(20)

     label                                               text
9339   ham  girls lie when they say size doesn't matter th...
5013   ham  want to have better sex you dont need viagra y...
7394  spam  the triplot function in the teachingdemos pack...
8280   ham  dear valued member with this special pharmaceu...
619   spam  on thu escapenumber escapenumber escapenumber ...
1721   ham  hi i am bored this evening i am escapenumber y...
537    ham  i just wanted to write and thank you for spur ...
3042   ham  buy x? . n?xmg 30 t?blets for only $ 119 . 95 ...
7208   ham  i strongly recommend you to switch to the cana...
3323  spam  the california litigation team weekly conferen...
4868   ham  all titles escapenumbern speclal on apr escape...
6323  spam  see escapenumber http rt perl org rtescapenumb...
1749  spam  start date : 1 / 29 / 02 ; hourahead hour : 6 ...
9914   ham  this gem is really movable lookup asvpcurrent ...
9068  spam  the methanol plant has determined extensive re...
8205   ham  good day\nvisit our new name - brand oem softw...
2769  spam  start date : 2 / 2 / 02 ; hourahead hour : 12 ...
6041   ham  dear valued member its your therapists assis...
3358  spam  this is just a friendly reminder that the opm ...
8726   ham  all titles escapenumbern speclal on apr escape...

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9989 entries, 0 to 9988
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   label   9989 non-null   object
 1   text    9989 non-null   object
dtypes: object(2)
memory usage: 156.2+ KB

In [10]:
all_words = ' '.join(df.text).split()

In [11]:
len(all_words)

2747483

In [12]:
count = Counter(all_words)
count

Counter({'into': 2295,
         'the': 85264,
         'kingdom': 49,
         'of': 40427,
         'god': 275,
         'and': 42360,
         'those': 1104,
         'that': 17078,
         'are': 10055,
         'entering': 58,
         'in': 28900,
         'he': 3506,
         'lord': 81,
         'pardon': 19,
         'escapenumber': 133208,
         'us': 3213,
         'this': 16485,
         'thing': 580,
         'we': 9072,
         'pray': 32,
         'thee': 22,
         'have': 10014,
         'excused': 1,
         'escapenumbernot': 3,
         'therefore': 310,
         'o': 1720,
         'believers': 14,
         'to': 56587,
         'look': 1183,
         'grave': 25,
         'for': 22671,
         'you': 22222,
         'it': 13230,
         'holy': 52,
         'ghost': 24,
         'being': 1141,
         'a': 36859,
         'habitation': 3,
         'unto': 39,
         'forth': 87,
         'words': 272,
         'truth': 101,
         'soberness': 2,
         'but': 5908,
         'all': 6834,
         'probability': 28,
         'hath': 7,
         'made': 1197,
         'them': 1818,
         'mad': 31,
         'though': 493,
         'blessed': 36,
         'be': 12177,
         'do': 5213,
         'jesus': 48,
         'christ': 92,
         'they': 3151,
         'see': 2633,
         'necessity': 73,
         'closing': 61,
         'with': 13249,
         'more': 5231,
         'than': 2126,
         'almost': 318,
         'christians': 31,
         'is': 21731,
         'heaven': 49,
         'so': 3523,
         'small': 487,
         'trifle': 7,
         "men's": 7,
         'esteem': 19,
         'as': 11360,
         'not': 9285,
         'total': 542,
         'renovation': 7,
         'whole': 345,
         'man': 618,
         'by': 8574,
         'righteousness': 28,
         'complete': 527,
         'delivered': 124,
         'from': 10399,
         'power': 1679,
         'candle': 8,
         'shines': 5,
         'out': 3393,
         'your': 12109,
         'redeemer': 5,
         'lifts': 10,
         'up': 3350,
         'inward': 1,
         'holiness': 6,
         'indeed': 119,
         'sometimes': 148,
         'worms': 4,
         'destroy': 58,
         'yet': 501,
         'even': 1180,
         'their': 2624,
         'flesh': 59,
         'shall': 494,
         'mind': 295,
         'then': 1959,
         'cannot': 520,
         'come': 817,
         'him': 1059,
         'jeannine': 1,
         'walsh': 20,
         'there': 3174,
         'was': 5531,
         'flow': 206,
         'at': 9395,
         'hpl': 230,
         'meter': 222,
         '1505': 1,
         'on': 16397,
         'april': 650,
         'first': 1729,
         'didn': 87,
         "'": 7816,
         't': 3217,
         'deal': 1077,
         'ticket': 271,
         '.': 52672,
         'now': 3350,
         'cover': 187,
         '740374': 1,
         'please': 4716,
         'link': 620,
         'or': 9107,
         'whatever': 147,
         'make': 2248,
         'work': 1973,
         'thanks': 2019,
         'lee': 169,
         'take': 1380,
         'one': 4241,
         'campaign': 227,
         'bvyhprice': 11,
         'day': 1959,
         'target': 560,
         'price': 2828,
         'escapenumbermarket': 64,
         'hellish': 52,
         'sym': 122,
         'gaining': 42,
         'momentum': 65,
         'news': 2717,
         'theescapenumber': 94,
         'call': 1260,
         'broker': 434,
         'somu': 6,
         'wrote': 1656,
         'actually': 405,
         'thats': 49,
         'what': 3569,
         'i': 19917,
         'looking': 1090,
         'l': 1220,
         'r': 6458,
         'if': 7868,
         'user': 713,
         'entered': 144,
         'string': 551,
         'matched': 21,
         "'lpt'": 1,
         "i'll": 214,
         'use': 2650,
         'p': 2376,
         'match': 222,
         "'npr'": 1,
         'n': 1110,
         'need': 2393,
         'tell': 454,
         'exactly': 225,
         'want': 1708,
         'otherwise': 200,
         "can't": 332,
         'whether': 467,
         'something': 812,
         'will': 8633,
         'simply': 440,
         'checking': 173,
         'input': 231,
         'contains': 301,
         'characters': 98,
         'would': 3962,
         'forget': 134,
         'about': 3589,
         'sorting': 14,
         'program': 1005,
         'below': 846,
         'explain': 126,
         'problem': 871,
         'instead': 373,
         'asking': 165,
         'how': 2393,
         'implement': 66,
         'solution': 411,
         'which': 3496,
         'may': 4195,
         'optimal': 23,
         'hth': 69,
         'rob': 84,
         'strict': 106,
         'warnings': 96,
         'print': 630,
         'match\\\\n': 1,
         "'orql'": 1,
         "'lor'": 1,
         'sub': 244,
         'my': 5112,
         'foreach': 73,
         'split': 177,
         "''": 286,
         'return': 1285,
         'unless': 195,
         '\\\\q': 1,
         'unsubscribe': 1525,
         'e': 4377,
         'mail': 2529,
         'beginners': 525,
         'perl': 1417,
         'org': 5109,
         'additional': 756,
         'commands': 337,
         'help': 4245,
         'http': 9844,
         'learn': 621,
         'fathi': 2,
         'boudra': 1,
         'fixed': 228,
         'issue': 542,
         'svn': 142,
         'repo': 9,
         'rev': 1380,
         'fix': 316,
         'dir': 168,
         'config': 343,
         'path': 400,
         'kdeglobals': 2,
         'kdesktoprc': 2,
         "doesn't": 413,
         'support': 891,
         'symlink': 7,
         'can': 5451,
         'prepare': 88,
         'an': 5825,
         'updated': 189,
         'package': 698,
         'included': 270,
         'etch': 63,
         'rescapenumber': 188,
         'address': 1037,
         'daniel': 59,
         'baumann': 11,
         'burgunderstrasse': 2,
         'ch': 2504,
         'biberist': 2,
         'email': 2657,
         'panthera': 4,
         'systems': 471,
         'net': 1676,
         'internet': 821,
         'people': 1719,
         'debian': 817,
         'desktop': 217,
         'request': 789,
         'lists': 703,
         'subject': 2255,
         'trouble': 259,
         'contact': 1510,
         'listmaster': 127,
         'categories': 48,
         'company': 3255,
         'guidefood': 1,
         'beverage': 57,
         'dad': 41,
         'ami': 57,
         'front': 171,
         'afterward': 6,
         'life': 885,
         'heck': 13,
         'naysayers': 1,
         'chill': 40,
         'seconds': 78,
         'doorsor': 1,
         'lookat': 1,
         'theother': 1,
         'forone': 1,
         'driveris': 1,
         'usedto': 4,
         'passenger': 11,
         'lessen': 6,
         'risk': 691,
         'pcprovide': 1,
         'critical': 123,
         'defense': 62,
         'firewall': 15,
         'sensitive': 44,
         'shared': 152,
         'joining': 99,
         'toolsprint': 1,
         'pageemail': 1,
         'trademarks': 85,
         'forpowered': 1,
         'dilemmas': 5,
         'troubled': 32,
         'souls': 23,
         'dealt': 112,
         'offered': 243,
         'features': 299,
         'component': 116,
         'restore': 56,
         'damaged': 37,
         'deleted': 298,
         'digitally': 10,
         'shreds': 3,
         'notfound': 1,
         'error': 1162,
         'achieving': 25,
         'ieclone': 1,
         'vanished': 19,
         'location': 239,
         'atlantis': 79,
         'paradise': 7,
         'bahamas': 5,
         'nassau': 2,
         'hotel': 77,
         'room': 317,
         'traveler': 4,
         'bauxite': 7,
         'derailment': 1,
         'biggest': 143,
         'evacuation': 5,
         'matter': 398,
         'ofmaking': 1,
         'category': 134,
         'subproblem': 1,
         'friendlyso': 1,
         'editors': 29,
         'cut': 300,
         'ctrlx': 1,
         'kevin': 198,
         'fighting': 52,
         'force': 178,
         'trained': 21,
         'deployed': 12,
         'moments': 42,
         'off': 1101,
         'spectrum': 20,
         'compass': 7,
         'quiz': 9,
         'advocates': 27,
         'russells': 1,
         'alliance': 41,
         'determined': 66,
         'describing': 19,
         'increase': 439,
         'deploying': 6,
         'behind': 225,
         'installing': 93,
         'needededit': 3,
         'hahahhah': 1,
         'haedit': 1,
         'sentiments': 3,
         'captured': 26,
         'word': 319,
         'bravoby': 1,
         'megatogon': 1,
         'andymukon': 1,
         'loyalty': 15,
         'bbc': 336,
         'blade': 13,
         'rack': 10,
         'optimized': 10,
         'server': 675,
         'io': 135,
         'choose': 318,
         'payroll': 19,
         'deflect': 1,
         'diggsgood': 1,
         'factors': 188,
         'kids': 154,
         'whiling': 1,
         'frivolous': 3,
         'pursuitsby': 1,
         'anaswasion': 1,
         'stored': 73,
         'encryption': 25,
         'stolen': 86,
         'alert': 513,
         'name': 1936,
         'bush': 822,
         'officers': 106,
         'ex': 141,
         'cia': 39,
         'chief': 263,
         'tenet': 24,
         "'failed'": 2,
         'leader': 124,
         'pm': 2036,
         'edt': 125,
         'letter': 364,
         'written': 228,
         'saturday': 355,
         'former': 270,
         'director': 288,
         'george': 236,
         'six': 216,
         'described': 93,
         'boss': 41,
         'alberto': 32,
         'gonzales': 55,
         'intelligence': 92,
         'community': 304,
         'called': 436,
         'his': 2601,
         'book': 454,
         'admission': 14,
         'failed': 413,
         'leadership': 61,
         'full': 1093,
         'story': 932,
         'agreed': 337,
         'receive': 1040,
         'cnn': 1355,
         'com': 8889,
         'result': 788,
         'preference': 137,
         'settings': 291,
         'manage': 346,
         'click': 1612,
         'here': 3160,
         'alter': 134,
         'criteria': 97,
         'frequency': 90,
         'receiving': 403,
         'custom': 156,
         'alerts': 203,
         'refer': 135,
         'friend': 389,
         'colleague': 94,
         "cnn's": 87,
         'free': 1959,
         'personalized': 95,
         'alerting': 65,
         'service': 1474,
         'cable': 316,
         'network': 900,
         'lp': 230,
         'lllp': 156,
         'center': 601,
         'atlanta': 189,
         'georgia': 188,
         '©': 141,
         'time': 3419,
         'warner': 138,
         'rights': 792,
         'reserved': 555,
         'terms': 644,
         'under': 1118,
         'provided': 534,
         'read': 2205,
         'our': 6959,
         'privacy': 426,
         'guidelines': 180,
         'vacation': 60,
         'carry': 101,
         '-': 40970,
         'over': 2034,
         'report': 1431,
         'due': 641,
         'end': 1073,
         'week': 1087,
         'days': 739,
         'system': 1448,
         'shows': 189,
         'let': 985,
         'me': 3841,
         'know': 2302,
         'correct': 234,
         'soon': 501,
         'possible': 739,
         'vince': 978,
         'kaminski': 545,
         '40': 252,
         '00': 1286,
         'hours': 541,
         'stephen': 98,
         'bennett': 13,
         '30': 747,
         'anita': 42,
         'dupont': 26,
         '14': 315,
         'seksan': 8,
         'kiatsupaibul': 4,
         '20': 606,
         'sandeep': 15,
         'kohli': 4,
         'kate': 56,
         'lucas': 8,
         'youyi': 3,
         'feng': 63,
         '36': 143,
         'shane': 16,
         'green': 228,
         'jose': 48,
         'marquez': 8,
         'moore': 74,
         '13': 294,
         'mike': 358,
         'roberts': 69,
         'sam': 82,
         'smith': 239,
         '10': 1350,
         '50': 456,
         'hector': 15,
         'campos': 12,
         'rabi': 3,
         'de': 1757,
         'shalesh': 12,
         'ganjoo': 11,
         'paulo': 34,
         'issler': 13,
         'martin': 222,
         'lin': 15,
         'zimin': 39,
         'lu': 34,
         'kenneth': 65,
         'parkhill': 3,
         'roman': 33,
         'zadorozhny': 5,
         'joe': 129,
         'hrgovcic': 5,
         'nelson': 28,
         'neale': 4,
         'vasant': 53,
         'shanbhogue': 32,
         '28': 226,
         'lance': 37,
         'cunningham': 11,
         '4': 1156,
         'tom': 210,
         'halliburton': 5,
         'alex': 60,
         'huang': 14,
         'praveen': 7,
         'mellacheruvu': 5,
         'jason': 48,
         'sokolov': 4,
         '8': 827,
         '32': 127,
         'tanya': 46,
         'tamarchenko': 18,
         'sevil': 14,
         'yaman': 8,
         '!': 3784,
         'shirley': 180,
         'lncrease': 4,
         'sprm': 1,
         'volume': 226,
         ',': 39261,
         'orgsm': 1,
         'length': 429,
         'main': 373,
         'benifits': 4,
         'longest': 13,
         'most': 1565,
         'intense': 30,
         'orga': 1,
         'zms': 1,
         'eerctions': 1,
         'like': 2912,
         'steel': 58,
         'enhancced': 1,
         'libido': 30,
         '/': 19489,
         'desire': 136,
         'stronger': 65,
         'ejacculaton': 1,
         'multple': 1,
         '_': 5810,
         ';': 2837,
         'asms': 1,
         '5': 1381,
         'oo': 238,
         '%': 1225,
         '(': 5487,
         'her': 1481,
         ')': 5871,
         'studies': 84,
         'show': 765,
         'tastes': 16,
         'alot': 30,
         'sweeter': 7,
         'dlscreet': 3,
         'same': 1060,
         'shipping': 326,
         'try': 994,
         'll': 272,
         'love': 386,
         'she': 1357,
         'no': 4526,
         'dont': 84,
         'respect': 232,
         'hobby': 13,
         'putting': 81,
         'armpit': 1,
         'farts': 1,
         'portion': 68,
         'convinced': 35,
         'pushing': 24,
         'buttons': 45,
         'xaroth': 1,
         'xfire': 1,
         'mtvn': 1,
         'property': 322,
         'modell': 2,
         'put': 561,
         'multi': 120,
         'part': 1069,
         'message': 2531,
         'mime': 69,
         'format': 320,
         'picked': 112,
         'text': 589,
         'plain': 217,
         'multipart': 24,
         'alternative': 429,
         'two': 1569,
         'pleasantly': 6,
         'dim': 39,
         'articles': 114,
         'indian': 120,
         'patent': 313,
         'law': 481,
         'provide': 1881,
         'comic': 31,
         'relief': 67,
         'barun': 1,
         'mitra': 2,
         'puts': 54,
         'feeble': 7,
         'issues': 470,
         'quite': 326,
         'grasp': 15,
         'beta': 65,
         'hindustantimes': 1,
         'storypage': 3,
         'aspx': 55,
         'id': 981,
         'escapelong': 24634,
         'aescapenumberb': 8,
         'roger': 60,
         'bate': 3,
         'wags': 1,
         'tail': 46,
         'www': 4567,
         'aei': 8,
         'publications': 80,
         'filter': 72,
         'pubid': 3,
         'pub': 23,
         'detail': 103,
         'asp': 104,
         'only': 3201,
         'deduce': 4,
         'fellows': 19,
         'tropical': 16,
         'consorts': 1,
         'inferior': 4,
         'connections': 41,
         'superior': 97,
         'reading': 238,
         'skills': 101,
         'never': 633,
         'mashelkar': 10,
         'himself': 158,
         'has': 4744,
         'said': 2627,
         'nothing': 497,
         'sec': 257,
         'd': 2198,
         'sarai': 1,
         'pipermail': 9,
         'commons': 28,
         'february': 184,
         'html': 2592,
         'says': 615,
         "he's": 105,
         'agreement': 496,
         'section': 483,
         'benchmarks': 14,
         'set': 1097,
         'depends': 60,
         'entirely': 83,
         'any': 3963,
         'individual': 256,
         'country': 498,
         'decide': 123,
         'threshold': 24,
         'limits': 48,
         'through': 1390,
         'these': 2144,
         'thresholds': 3,
         'governments': 34,
         'exercise': 107,
         'control': 569,
         'upside': 23,
         'critics': 40,
         'enemies': 23,
         'who': 2025,
         'needs': 448,
         'friends': 257,
         'ip': 401,
         'health': 1167,
         'mailing': 1915,
         'list': 3579,
         'essential': 247,
         'mailman': 1666,
         'listinfo': 1535,
         'adobe': 973,
         'csescapenumber': 355,
         'extended': 132,
         'znausmotr': 1,
         'begin': 429,
         'pgp': 317,
         'signed': 268,
         'hash': 379,
         'ripemdescapenumber': 1,
         'ignore': 62,
         'signature': 234,
         'version': 1102,
         'gnupg': 161,
         'vescapenumber': 404,
         'mingwescapenumber': 14,
         'geibsyqfc': 1,
         'qiug': 1,
         'speakup': 810,
         'braille': 439,
         'uwo': 436,
         'ca': 1573,
         'speech': 344,
         'marcus': 21,
         'vinicius': 3,
         'dear': 965,
         "i'm": 942,
         'getting': 460,
         'packages': 333,
         'install': 401,
         'c': 5147,
         'exactranktests': 9,
         'trying': 533,
         'url': 238,
         'cran': 68,
         'project': 1757,
         'bin': 661,
         'windows': 877,
         'contrib': 16,
         "packages'": 3,
         'content': 420,
         'type': 1036,
         "plain'": 2,
         'bytes': 115,
         'opened': 117,
         'downloaded': 71,
         'escapenumberkb': 15,
         'means': 576,
         'using': 1450,
         'x': 4668,
         'really': 961,
         'ancient': 70,
         'upgrade': 74,
         'recent': 385,
         'before': 1290,
         'function': 930,
         'installed': 219,
         'load': 269,
         'library': 503,
         'uwe': 20,
         'ligges': 16,
         "zip'": 5,
         'application': 390,
         "'exactranktests'": 4,
         'successfully': 82,
         'unpacked': 7,
         'mdescapenumber': 25,
         'sums': 18,
         'checked': 101,
         'delete': 149,
         'files': 573,
         'y': 1519,
         'updating': 30,
         'descriptions': 18,
         'documentation': 206,
         'specified': 111,
         'libraries': 63,
         'could': 2182,
         "'help": 4,
         'search': 483,
         'lot': 510,
         'stat': 2490,
         'math': 1364,
         'ethz': 2396,
         'https': 1088,
         'posting': 2198,
         'guide': 2266,
         'commented': 1095,
         'minimal': 1092,
         'self': 1550,
         'contained': 1248,
         'reproducible': 1071,
         'code': 2181,
         'everything': 290,
         "you're": 330,
         'right': 1207,
         'focus': 236,
         'major': 527,
         'financial': 643,
         'released': 275,
         'after': 1781,
         'market': 1264,
         'close': 575,
         'today': 1268,
         'hot': 295,
         'china': 275,
         'voice': 294,
         'holding': 120,
         'corp': 831,
         'h': 1570,
         'v': 645,
         'short': 579,
         'term': 758,
         'expected': 451,
         'dollar': 109,
         "here's": 119,
         'completes': 36,
         'acquisition': 223,
         'streamjet': 1,
         'inc': 1286,
         'confirms': 23,
         'million': 934,
         'annual': 200,
         'revenue': 211,
         'go': 1595,
         'wake': 36,

In [13]:
df.label.info()

<class 'pandas.core.series.Series'>
RangeIndex: 9989 entries, 0 to 9988
Series name: label
Non-Null Count  Dtype
--------------  -----
9989 non-null   object
dtypes: object(1)
memory usage: 78.2+ KB

In [14]:
df.describe()

       label                                               text
count   9989                                               9989
unique     2                                               9989
top      ham  anatrim escapenumber the newest and most attra...
freq    5294                                                  1

In [15]:
df.label.value_counts()

label
ham     5294
spam    4695
Name: count, dtype: int64

> Cleaning Data

In [16]:
df.isna().sum()

label    0
text     0
dtype: int64

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
df = df.dropna()
all_words = ' '.join(df.text).split()

In [19]:
df = df.drop_duplicates()
df = df.dropna()

# حذف علامات الترقيم

In [20]:
punc = string.punctuation

In [21]:
punTable = str.maketrans('','',punc)

In [22]:
df.text = df.text.str.translate(punTable)

In [23]:
df

     label                                               text
0      ham  into the kingdom of god and those that are ent...
1     spam  there was flow at hpl meter 1505 on april firs...
2      ham  take a look at this one campaign for bvyhprice...
3     spam  somu wrote actually thats what i was looking f...
4     spam  fathi boudra wrote i fixed the issue in the sv...
...    ...                                                ...
9984   ham  this would be a great tragedy for all concerne...
9985   ham  hello  welcome to medzonline filamentous shop\...
9986   ham  this is amazing stuff add some inches fast saf...
9987  spam  author jra date escapenumber escapenumber esca...
9988   ham  anatrim escapenumber the newest and most attra...

[9989 rows x 2 columns]

# حروف صغيرة

In [24]:
df.text = df.text.str.lower()

# حذف الكلمات الشائعة

In [25]:
# nltk.download('stopwords')
# nltk.download('punkt')
stopWords = set(stopwords.words('english'))

In [26]:
df.text = df.text.str.split()

In [27]:
df.text = df.text.apply(lambda x:[word for word in x if word not in stopWords])

In [28]:
df.text= df.text.apply(lambda x:' '.join([word for word in x if len(word) > 2]))

In [29]:
df

     label                                               text
0      ham  kingdom god entering lord pardon escapenumber ...
1     spam  flow hpl meter 1505 april first deal ticket de...
2      ham  take look one campaign bvyhprice escapenumber ...
3     spam  somu wrote actually thats looking user entered...
4     spam  fathi boudra wrote fixed issue svn repo rev es...
...    ...                                                ...
9984   ham  would great tragedy concerned situation digiti...
9985   ham  hello welcome medzonline filamentous shop plea...
9986   ham  amazing stuff add inches fast safe effective s...
9987  spam  author jra date escapenumber escapenumber esca...
9988   ham  anatrim escapenumber newest attracting product...

[9989 rows x 2 columns]

# تحويل الكلمات إلى جذورها الأساسية أو صيغتها المعيارية

In [30]:
# nlp = spacy.load("en_core_web_sm")
# df['text'] = df['text'].apply(lambda x: " ".join([token.lemma_ for token in nlp(str(x))]))

In [31]:
df

     label                                               text
0      ham  kingdom god entering lord pardon escapenumber ...
1     spam  flow hpl meter 1505 april first deal ticket de...
2      ham  take look one campaign bvyhprice escapenumber ...
3     spam  somu wrote actually thats looking user entered...
4     spam  fathi boudra wrote fixed issue svn repo rev es...
...    ...                                                ...
9984   ham  would great tragedy concerned situation digiti...
9985   ham  hello welcome medzonline filamentous shop plea...
9986   ham  amazing stuff add inches fast safe effective s...
9987  spam  author jra date escapenumber escapenumber esca...
9988   ham  anatrim escapenumber newest attracting product...

[9989 rows x 2 columns]

# تقسيم البيانات

In [32]:
x = df.text
y = df.label

In [33]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

# هندسة الميزات

In [34]:
tfidf=TfidfVectorizer()

In [35]:
x_train_vec = tfidf.fit_transform(x_train)
x_test_vec = tfidf.transform(x_test)

# بناء النموذج

In [36]:
model = MultinomialNB()

In [37]:
model.fit(x_train_vec,y_train)

MultinomialNB()

In [38]:
pred = model.predict(x_test_vec)

In [39]:
acc = accuracy_score(pred,y_test)

In [40]:
acc

0.970970970970971

In [41]:
classification =classification_report(pred,y_test)

In [42]:
print(classification)

              precision    recall  f1-score   support

         ham       0.96      0.98      0.97      1035
        spam       0.98      0.96      0.97       963

    accuracy                           0.97      1998
   macro avg       0.97      0.97      0.97      1998
weighted avg       0.97      0.97      0.97      1998

In [43]:
import joblib

model_path = (
    "/kaggle/input/models/omar2716/emails-model/scikitlearn/default/1/spam"
)
loaded_model = joblib.load(model_path)
print("تم تحميل النموذج بنجاح:", type(loaded_model))

تم تحميل النموذج بنجاح: <class 'sklearn.pipeline.Pipeline'>

/usr/local/lib/python3.12/dist-packages/sklearn/base.py:380: InconsistentVersionWarning: Trying to unpickle estimator TfidfTransformer from version 1.2.2 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:380: InconsistentVersionWarning: Trying to unpickle estimator TfidfVectorizer from version 1.2.2 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:380: InconsistentVersionWarning: Trying to unpickle estimator LinearSVC from version 1.2.2 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:380: InconsistentVersionWarning: Trying to unpickle estimator Pipeline from version 1.2.2 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [44]:
joblib.dump(model, "spam.joblib")

['spam.joblib']

In [45]:
df.to_csv('output_spam.csv', index=False)

In [46]:
joblib.dump(model, 'spam_model.pkl')

['spam_model.pkl']